version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore Reception.sln
build_script:
  - cmd: dotnet build Reception.sln
test_script:
  - cmd: dotnet test Reception.Tests/Reception.Tests.csproj